name: Sync book to Fork

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config --global user.email "pierre.thoor@gmail.com"
          git config --global user.name "pthoor"

      - name: Add fork as remote
        run: git remote add fork https://github.com/pthoor/Packt-Microsoft-Defender-for-Identity-in-Depth.git

      - name: Force push changes to upstream
        run: git push fork main:main --force