name: Sync Fork from Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config --global user.email "pierre.thoor@gmail.com"
          git config --global user.name "pthoor"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/PacktPublishing/Microsoft-Defender-for-Identity-in-Depth.git

      - name: Force push changes to upstream
        run: git push upstream main --force