name: Sync Main Branch to Packt Publishing repo
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config --global user.email "pierre.thoor@gmail.com"
          git config --global user.name "pthoor"

      - name: Add target repository as a remote
        run: git remote add target https://github.com/PacktPublishing/Microsoft-Defender-for-Identity-in-Depth

      - name: Push changes to the target repository
        run: |
          git fetch target
          git push target main:main
